### ISSUE TITLE
DEP 0210, some annotations

### ISSUE THREAD

**Issue by jrief** [django/deps#35]
### Instead of a type ``string`` I would use ``slug``
The terminology slug is widely used in Django and everybody knows that it is a string without whitespace, slashes and other special characters, while string has a much wider scope of application.

### Do not offer a type ``float``
First, I don't see any use-case for floats, but more important, numbers of type float sometimes are localized using a comma as a decimal separator instead of the dot. This would allow two different URLs for the same Django view and this therefore can be very confusing.

**Comment by timgraham** [comment]
It seems the DEP has been revised such that these comments are no longer applicable.
1. `slug` is a separate converter.
2. `float` is not offered.
