### ISSUE TITLE
New DEP's related to composite primary key and other related improvement of django based on previous works

### ISSUE THREAD

**Issue by auvipy** [django/deps#38]
compare and re assess https://gist.github.com/koniiiik/5408673 too

**Comment by auvipy** [comment]
and this one too with the approach of 2 existing draft dep

**Comment by auvipy** [comment]
and this ticket https://code.djangoproject.com/ticket/373

**Comment by auvipy** [comment]
https://code.djangoproject.com/ticket/24317 this might need a separate DEP

**Comment by auvipy** [comment]
https://code.djangoproject.com/ticket/16508 this needs attention too

**Comment by evildmp** [comment]
@auvipy your interest is appreciated, but this is not the correct way to use Issues for DEPs.

Issues should be used to point out a specific problem, or an opportunity for improvement, in an existing DEP, or to comment on one.

Nobody is going to create a DEP based on an issue (at least not like this). Even to start moving, never mind actually to get off the ground, a DEP requires a substantial amount of thought, writing, discussion and other work.

See https://github.com/django/deps/pull/36/commits/6e5ef49f8d08793e0d6906baa198db47629bf93e for an example of how much work has to go into what the author calls "a first pre-draft".
