### ISSUE TITLE
Draft Proposal: Django Mergers with Terms

### ISSUE THREAD

**Issue by collinanderson** [django/deps#50]
Hi All,

I want to at least outline an alternative proposal based on feedback from James’ PR ( https://github.com/django/deps/pull/47 ). And I’d like to propose an actual process for selecting Mergers.

Jacob summarized the biggest problem I see with the current core team: “The problem (as I see it) is that we're currently also recognizing people for (long-)past contributions, giving them power and status that may not be appropriate any more.”

Roughly, I think it should have these features:

- There should still be recognition / “perceived status” associated with the mergers (not just bureaucratic), but only active contributors actually actually get that status.
- There should be a way for people to try out being a merger for a period of time (to encourage more people to get involved)
- You need to opt-in regularly to continue being a merger, though it’s really easy to do.
- There should be a natural time to stop being an active merger, but it should be really easy to become an active merger again. (Stepping down isn’t irreversible.) (Could help with burnout, too)
- There should be an activity requirement for mergers, but not an actual limit to the number of mergers as long as they’re active enough.
- Tech board is elected by django-developers

Proposal:

Mergers

- Mergers regularly review tickets, author patches, and/or review and merge patches
- They are expected to be contributing regularly on a weekly basis 
- They only commit to being a Merger for one release cycle at a time (a term). Maybe the term ends about a month after a release of Django, just after the x.x.1 release.
- Mergers don’t automatically get push access to Django, but can ask for access at any time. The request gets voted on by the tech board. (so not exactly “merger means push access”, but similar to current/former core team) (also, other roles could have push access, like security team, releasers, etc, so push access isn’t exclusive to mergers, though that’s out of scope for this proposal)
- If you stop being a merger, you no longer get push access (or other permissions) to Django (again, unless you have some other role like security team, or board members can retain push access)

There are two types of mergers: Core Mergers and Guest Mergers.

Guest Mergers

- Anyone can apply/request at any time to be a Guest Merger by filling out a google form, though they should have some recent contribution history before applying.
- There should be a call for Guest Mergers at the beginning of a new term. (and anyone should also encourage anyone to apply)
- Applicants are reviewed (and possibly interviewed) by the Core Mergers and they make a recommendation to the tech board to approve or disapprove. If tech board approves, this gets announced on django-developers.
- It’s expected that guest mergers need oversight and help from the core mergers.
- Any core merger can revoke Guest Merger push access (or other access) at any time.
- At the end of their term, if a Guest Merger wants to continue being a Merger they need to re-apply.
- (There’s nothing wrong with just serving one term as Guest Merger and then stepping down. That’s welcomed. You can always apply be a Guest Merger again later.)
- You can’t serve more than two full consecutive terms as a Guest Merger (either Core Mergers need to invite you to be a Core Merger, or you need to take a break)

Core Mergers
- Core Mergers (as a group) can invite anyone who has served a full term as Guest Merger to be a Core Merger. This gets voted on by the tech board and if approved, announced to django-developers.
- Any former Core Merger, or former core team member can become a Core Merger by publicly requesting this on django-developers at any time. (There’s an expectation that they’ll then be fairly active until the end of that term.) This gets voted on by the tech board and if approved, announced on django-developers.
- At the end of their term, Core Mergers simply need to say something like “i’m interested in continuing to be a merger” publicly on django-developers. This also gets voted on by the tech board (tech board should confirm that they’ve been regularly reviewing tickets, patches, etc over their term.)
- There’s no limit to the number of consecutive terms a Core Merger can serve.

 
Though normally not needed, both DSF board and Tech board have the right make exceptions or to add or remove anyone from any of these roles at any time.

(I like the term “Merger” because it’s the only thing Mergers can do that other people can’t do. “Guest Reviewer” for example makes it sound like other people aren’t allowed to review, and “core team” doesn’t explain what they do as well. You can also be an “active” contributor without being active enough to qualify for the “merger” role. I think “Committer” is also an ok term.)

Also, just like currently, anyone (besides the patch writer) can mark a ticket/patch as “ready for check-in”, and mergers shouldn’t be committing their own stuff without review. I don’t see the need for any changes there. I don’t see any need to change anything about the release process either.

I also think we need better transparency as to who actually has permissions to what, security team and ops teams might also need terms, we somehow need to recognize “moderator” roles on django-users and irc channels, etc, but that’s all out of scope for this proposal.

**Comment by jarshwah** [comment]
I like the idea you've raised of a Guest merger. It tries to attract new talent under a mentoring type of arrangement. I wonder how it might work in practise though. Would the core mergers be able to put in the time to effectively train the juniors? I think this could open up "core work" to a more diverse group

Term limits I think are necessary, with an explicit opt in to continue into the next term, and the possibility to pick the role back up after stepping down for some time.

Some specific criticisms: 

- Mergers should get commit access, otherwise what's the point
- A limit of 2 terms as a guest seems strange, but seems like a guard against forever-guest-merger
- After each release, the release manager or tech board should open a call for mergers (core and guest) which serves as the opt in trigger

**Comment by collinanderson** [comment]
> Mergers should get commit access, otherwise what's the point

Well, my thought is, especially for "Guest Mergers" you could still do a lot of ticket triage and patch review, which is really helpful and worth recognition, without technically needing commit access. 

> A limit of 2 terms as a guest seems strange, but seems like a guard against forever-guest-merger

2 _consecutive_ terms. Maybe not really necessary, but yeah, my thought is to show a clear path to Core Merger: do two guest merger terms in a row and you're basically in (assuming the Core Mergers want to keep you around). I'm also starting to second-guess the 8-month length of Guest Merger, maybe we should allow beginners to only need to commit to 4 months?
 
> After each release, the release manager or tech board should open a call for mergers (core and guest) which serves as the opt in trigger

Seems fine to me.

**Comment by timgraham** [comment]
I don't know. It feels like the DSF would be promoting forced, unpaid labor to ask people to volunteer as guest mergers and then require them to be active every week. I would be surprised if many people volunteer for this, but I could be wrong.

**Comment by collinanderson** [comment]
My thinking is the Guest Merger is sort of a training period, and to get trained you need to be at least somewhat active. My hope is to provide people a clear path to being Core Mergers which requires being somewhat active. If anything I could see the 9-month term being shortened to 3-4 months, so they don't need to be super active for as long of a period of time.

**Comment by carltongibson** [comment]
Closing as part of the (resolved) DEP 10 discussion. Thanks all.
