### ISSUE TITLE
DEP 9: Please do not ignore the async-only usecase

### ISSUE THREAD

**Issue by abetkin** [django/deps#60]
- For how long you have considered making django async-only?
- (Andrew Godwin) For about 2 minutes.

@andrewgodwin yes, I decided to write this after watching the presentation you gave at PyConAu 2019

summary
--------
Please consider the usecase where a developer doesn't want to mix sync and async code, but rather has a sync application and a (separate) async application and wants them to have common parts (for example, definitions of the models).

the accepted approach (DEP 9)
-------

The stated goal was to enable async in django, while preserving backwards compatibility. The accepted approach is to make some parts of django async. Partly because it allows you to have synchronous parts in your async application (that are easier to write), partly because django is big and its migration to async is better to be gradual (thus having a lot of sync parts at start).

To provide that, it is proposed to use something like `asgiref.sync_to_async` and `asgiref.async_to_sync` adapters. The important detail is that it pins all sync handlers for a given request to a single thread.

downsides
-------

- sync parts exist = we still have the slowdown
- the implementation is complicated. We are going from sync to async and back, possibly multiple times. We are required to make sync parts to be executed in the same thread, that means we cannot just use the first available thread, hence more slowdown
- long-polling (one of the examples that will benefit from django 3.0) is quite exotic

async-only?
---------
Well, it doesn't mean async-only, but it does mean that you cannot mix sync and async code. You can have gunicorn serving the sync handlers and twisted serving the async handlers, both using the same database, config, etc. Actually, you can use that approach today. Just the amount of code you can reuse between sync and async applications is close to 0. That can be improved: the async part of django is unwritten yet, and we have some degree of freedom.

orm
--------

The models are mostly declarative, so conceptually there shouldn't be problems here. The same declarations of models can be used for sync and async code. Let migrations be synchronous only. Let django-admin be synchronous only.

middleware
-----------

Middleware will have to be implemented differently for sync and async cases. It would be nice if we could still reference same things in the configuration, like this:

```
MIDDLEWARE = [
    'common.SessionMiddleware',
    'common.AuthenticationMiddleware',
]
```

Here `common.SessionMiddleware` can be an empty class, an actual implementation being provided separately for sync and async cases.

DEP 9?
-----

While I am personally for async-only django, that is configuration-compatible with traditional django, rather then for DEP 9, they do not exclude each other. I guess that a lot of implementation code of DEP 9 will be useful in async-only usecase anyway. I am just asking to add it as a legit usecase to avoid bad API design.

Also, if you know a proper place for this writing, please tell me.

**Comment by andrewgodwin** [comment]
Hi - this is not the appropriate place to discuss a DEP, please instead raise it on the django-developers mailing list.

However, I do want to say that your use case is what I'm aiming for anyway - namely, that the two modes are async-only (async mode) and sync with some async (sync mode). If you run async code in Django when DEP is finished, there'll be no sync code running in the same stack.

**Comment by abetkin** [comment]
@andrewgodwin  Thanks for your answer. I see that it is one of eventual goals of DEP 9, I think that will be enough. Not sure now if it makes sense to raise this on django mailing lists, since it's not directly related to DEP 9. This is not a DEP too, since most work on enabling async-only usecase, if not all, can be done in a third-party package. And since nothing stops anyone from implementing this, it may be a more reasonable than discussing. The enabling of async usecase is gradual effort as well: over time, more and more configuration/code could be shared between the traditional and async django. Btw, is the current implementation code of DEP 9 public?

**Comment by andrewgodwin** [comment]
DEP 9 is not a single implementation; it's ongoing. The current part of it that is in progress is in https://github.com/django/django/pull/11650
