### ISSUE TITLE
Document the current DEP process

### ISSUE THREAD

**Issue by thibaudcolas** [django/deps#80]
Can we have documentation for the DEP process as it stands at this point in time, combining what appears to be three different documents?

---

The README states:

> See [DEP 1](https://github.com/django/deps/blob/main/final/0001-dep-process.rst) for details.

Said DEP refers to the Technical Board and to Core Developers, two groups which no longer exist as far as I know. 

We have the same issue in Django’s contributor documentation:

> Changes to this document require the use of the [DEP process](https://github.com/django/deps/blob/main/final/0001-dep-process.rst), with modifications described in [DEP 0010](https://github.com/django/deps/blob/main/accepted/0010-new-governance.rst#changing-this-governance-process).

DEP 10 is also no longer up-to-date with how Django operates. So – in order to write a DEP, I have to read at least DEP 1, 10, and 12.

**Comment by carltongibson** [comment]
> FWIW: I don't think we have to keep DEPs frozen in time. ... 

There was some umm-ing and err-ing about this when discussing DEP 12 — Are they living documents, or historical records? (I have no great opinion, but clarifying would help.)

**Comment by jacobian** [comment]
Indeed, I was one of the um-and-err-ers -- but I now think that having them be fixed static documents cause problems for no real benefit. But yeah, we should clarify -- in an updated DEP 1. We can have the conversation in that PR or on the mailing list/forum etc.
